from . import hms_hr_ext
from . import hms_master
from . import hms_patient_ext
from . import hms_opd_visit
from . import hms_procedure
from . import hms_visit_type
from . import hms_icd10
from . import hms_patient_snapshot
from . import hms_triage
from . import hms_vitals
from . import hms_queue
from . import hms_opd_consumable
from . import hms_dept_requisition
